export enum RoomStatus {
  AVAILABLE = 'AVAILABLE',
  OCCUPIED = 'OCCUPIED',
  RESERVED = 'RESERVED',
  MAINTENANCE = 'MAINTENANCE',
  CLEANING = 'CLEANING',
  OUT_OF_ORDER = 'OUT_OF_ORDER',
}

export enum RoomType {
  SINGLE = 'SINGLE',
  DOUBLE = 'DOUBLE',
  SUITE = 'SUITE',
  DELUXE = 'DELUXE',
  PRESIDENTIAL = 'PRESIDENTIAL',
}

export enum BookingStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  CHECKED_IN = 'CHECKED_IN',
  CHECKED_OUT = 'CHECKED_OUT',
  CANCELLED = 'CANCELLED',
  NO_SHOW = 'NO_SHOW',
}

export enum BookingSource {
  DIRECT = 'DIRECT',
  WALK_IN = 'WALK_IN',
  BOOKING_COM = 'BOOKING_COM',
  AIRBNB = 'AIRBNB',
  EXPEDIA = 'EXPEDIA',
  AGODA = 'AGODA',
  OTHER_OTA = 'OTHER_OTA',
}

export enum ServiceType {
  ROOM_SERVICE = 'ROOM_SERVICE',
  LAUNDRY = 'LAUNDRY',
  SPA = 'SPA',
  RESTAURANT = 'RESTAURANT',
  MAINTENANCE = 'MAINTENANCE',
  CONCIERGE = 'CONCIERGE',
  OTHER = 'OTHER',
}

export enum ServiceStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum HousekeepingStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  INSPECTED = 'INSPECTED',
}

export enum InvoiceStatus {
  DRAFT = 'DRAFT',
  PENDING = 'PENDING',
  PAID = 'PAID',
  PARTIALLY_PAID = 'PARTIALLY_PAID',
  OVERDUE = 'OVERDUE',
  CANCELLED = 'CANCELLED',
}

export enum PaymentMethod {
  CREDIT_CARD = 'CREDIT_CARD',
  DEBIT_CARD = 'DEBIT_CARD',
  CASH = 'CASH',
  BANK_TRANSFER = 'BANK_TRANSFER',
  DIGITAL_WALLET = 'DIGITAL_WALLET',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
  PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED',
}

export enum NotificationType {
  CHECK_IN = 'CHECK_IN',
  CHECK_OUT = 'CHECK_OUT',
  BOOKING_CONFIRMATION = 'BOOKING_CONFIRMATION',
  BOOKING_CANCELLATION = 'BOOKING_CANCELLATION',
  SERVICE_REQUEST = 'SERVICE_REQUEST',
  COMPLAINT = 'COMPLAINT',
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  HOUSEKEEPING_ALERT = 'HOUSEKEEPING_ALERT',
  SYSTEM = 'SYSTEM',
}

export enum EmailType {
  WELCOME = 'WELCOME',
  BOOKING_CONFIRMATION = 'BOOKING_CONFIRMATION',
  CHECK_IN_REMINDER = 'CHECK_IN_REMINDER',
  CHECK_OUT_THANK_YOU = 'CHECK_OUT_THANK_YOU',
  LOYALTY_DISCOUNT = 'LOYALTY_DISCOUNT',
  PROMOTIONAL = 'PROMOTIONAL',
  PASSWORD_RESET = 'PASSWORD_RESET',
}
