import { useState } from 'react';
import clsx from 'clsx';
import { useParallax } from '../../hooks/useParallax';

interface ImgProps {
  src: string;
  alt: string;
  /** container classes — set the aspect ratio / size here */
  className?: string;
  imgClassName?: string;
  /** eager-load (use for the hero / above-the-fold imagery) */
  priority?: boolean;
  /** scroll-linked vertical parallax (image is oversized to avoid gaps) */
  parallax?: boolean;
  parallaxSpeed?: number;
  /** responsive `sizes` hint for the srcset (defaults to full viewport width) */
  sizes?: string;
}

// Raster sources get optimized AVIF/WebP variants generated by
// scripts/optimize-images.mjs (e.g. heroMain-960.avif). Anything else (SVG,
// already-modern formats) is rendered as-is.
const RASTER_RE = /\.(png|jpe?g)$/i;
const WIDTHS = [480, 960, 1440];

function srcSet(src: string, ext: 'avif' | 'webp'): string {
  const base = src.replace(RASTER_RE, '');
  return WIDTHS.map((w) => `${base}-${w}.${ext} ${w}w`).join(', ');
}

/**
 * Cover image with a warm gradient fallback shown while loading or if the
 * source fails. Serves AVIF/WebP via <picture> with a PNG/JPG fallback, so the
 * universal `src` always works even if a variant is missing.
 */
export default function Img({
  src,
  alt,
  className,
  imgClassName,
  priority,
  parallax,
  parallaxSpeed,
  sizes = '100vw',
}: ImgProps) {
  const [loaded, setLoaded] = useState(false);
  const [failed, setFailed] = useState(false);
  const parallaxRef = useParallax<HTMLImageElement>({ speed: parallaxSpeed });

  const optimized = RASTER_RE.test(src);

  const img = (
    <img
      ref={parallax ? parallaxRef : undefined}
      src={src}
      alt={alt}
      loading={priority ? 'eager' : 'lazy'}
      decoding="async"
      sizes={sizes}
      onLoad={() => setLoaded(true)}
      onError={() => setFailed(true)}
      className={clsx(
        'object-cover transition-opacity duration-[900ms] ease-breath',
        parallax
          ? 'absolute inset-x-0 -top-[15%] h-[130%] w-full'
          : 'h-full w-full',
        loaded ? 'opacity-100' : 'opacity-0',
        imgClassName,
      )}
    />
  );

  return (
    <div className={clsx('img-fallback relative overflow-hidden', className)}>
      {!failed &&
        (optimized ? (
          // `contents` so the <picture> box doesn't break the <img> sizing/positioning
          <picture className="contents">
            <source type="image/avif" srcSet={srcSet(src, 'avif')} sizes={sizes} />
            <source type="image/webp" srcSet={srcSet(src, 'webp')} sizes={sizes} />
            {img}
          </picture>
        ) : (
          img
        ))}
    </div>
  );
}
